"""Initial database schema

Revision ID: c0911edc6beb
Revises: 
Create Date: 2025-05-12 10:05:35.155694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0911edc6beb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('sapo', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_date_str', sa.String(length=100), nullable=True),
    sa.Column('publish_datetime', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('total_comment_count', sa.Integer(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('main_topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_publish_datetime'), ['publish_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_url'), ['url'], unique=True)

    op.create_table('article_topics',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'topic_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('comment_api_id', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_date_str', sa.String(length=100), nullable=True),
    sa.Column('comment_datetime', sa.DateTime(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('replies_count', sa.Integer(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score_comment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_api_id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_comment_datetime'), ['comment_datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_comment_datetime'))
        batch_op.drop_index(batch_op.f('ix_comments_article_id'))

    op.drop_table('comments')
    op.drop_table('article_topics')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_url'))
        batch_op.drop_index(batch_op.f('ix_articles_publish_datetime'))
        batch_op.drop_index(batch_op.f('ix_articles_category'))

    op.drop_table('articles')
    op.drop_table('topics')
    # ### end Alembic commands ###
